# Generated by Django 2.0.5 on 2018-05-07 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tite',
            new_name='title',
        ),
    ]
